name: m68k_reloaded_parser
description: Compiler for Motorola 68000 Assembly converting source code into statements
version: 0.0.1
authors:
  - Marcel Garus <marcel.garus@gmail.com>
  - Jonas Wanke <contact@wanke.dev>
homepage: https://github.com/m68k-reloaded/sdk/tree/master/parser

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  data_classes: ^2.0.3
  meta: ^1.1.7
  collection: ^1.14.12
  kt_dart: ^0.7.0-dev.4

dev_dependencies:
  build_runner: ^1.7.1
  data_classes_generator: ^2.0.3

  test: ^1.9.2
